apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
    tier: backend
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - image: redislabs/redisgears:1.0.0
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
status: {}
